apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentic-email-processing-system-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: agentic-email-processing-system-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/agentic-email-processing-system
        property: DB_PASSWORD
    - secretKey: AI_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/agentic-email-processing-system
        property: AI_SERVICE_TOKEN

    - secretKey: JWT_TOKEN
      remoteRef:
        key: secret/prod/agentic-email-processing-system
        property: JWT_TOKEN
